---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: shinysorter-importdir-sc
provisioner: pxd.portworx.com
parameters:
  repl: "1"
  sharedv4: "true"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shinysorter-importdir
spec:
  storageClassName: shinysorter-importdir-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi