---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shinysorter-apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      volumes:
      - name: storagedir
        persistentVolumeClaim:
          claimName: shinysorter-storagedir
      containers:
      - name: apiserver
        image: adamukaapan/shinysorter-backend:latest
        imagePullPolicy: Always
        command:
        - '/restserver'
        - '--mongodb-connection-uri=mongodb://shinysorter:shiny_sorter@{{ include "shinysorter.fullname" . }}-mongodb:{{ .Values.mongodb.service.ports.mongodb }}/shiny_sorter'
        - '--storage-dir=/storage'
        - '--listen-port={{ .Values.apiServer.port }}'
        - '--log-level=debug'
        volumeMounts:
        - mountPath: /storage
          name: storagedir
        ports:
        - name: rest
          containerPort: {{ .Values.apiServer.port }}
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shinysorter.fullname" . }}-apiserver
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.apiServer.port }}
  selector:
    app: apiserver
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "shinysorter.fullname" . }}-apiserver
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.apiServer.prefix }}/api/?(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ include "shinysorter.fullname" . }}-apiserver
            port:
              number: {{ .Values.apiServer.port }}
