---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shinysorter-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: adamukaapan/shinysorter-frontend:latest
        imagePullPolicy: Always
        env:
        - name: API_SERVER_BASEPATH
          value: {{ trimPrefix "/" .Values.apiServer.prefix }}/api
        - name: BASEPATH
          value: {{ trimPrefix "/" .Values.frontend.prefix }}
        ports:
        - name: ui
          containerPort: 3000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shinysorter.fullname" . }}-frontend
spec:
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 3000
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "shinysorter.fullname" . }}-frontend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.frontend.prefix }}/?(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ include "shinysorter.fullname" . }}-frontend
            port:
              number: 3000