---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shinysorter-frontend-config
data:
  app.config.json: |
    {
      "apiServerAddress": "{{ .Values.apiServer.prefix }}/api"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shinysorter-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: frontend
        image: {{ .Values.frontend.image }}
        imagePullPolicy: Always
        env:
        - name: TARGET_BASE_PATH
          value: {{ trimPrefix "/" .Values.frontend.prefix }}
        ports:
        - name: ui
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/html/assets
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: shinysorter-frontend-config
            items:
            - key: "app.config.json"
              path: "app.config.json"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shinysorter.fullname" . }}-frontend
spec:
  ports:
    - protocol: TCP
      port: 80
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "shinysorter.fullname" . }}-frontend
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.frontend.prefix }}/
        pathType: Prefix
        backend:
          service:
            name: {{ include "shinysorter.fullname" . }}-frontend
            port:
              number: 80