### storage.yaml
# Contains the storage definitions for the project. Powered by Portworx, but
# can work with anything providing ReadWriteMany capabilities
###
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: shinysorter-mongo-sc
  annotations:
    helm.sh/hook: pre-install
provisioner: pxd.portworx.com
parameters:
  repl: "1"
  fs: "xfs"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: shinysorter-importdir-sc
  annotations:
    helm.sh/hook: pre-install
provisioner: pxd.portworx.com
parameters:
  repl: "1"
  sharedv4: "true"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shinysorter-importdir
spec:
  storageClassName: shinysorter-importdir-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: shinysorter-storagedir-sc
  annotations:
    helm.sh/hook: pre-install
provisioner: pxd.portworx.com
parameters:
  repl: "1"
  sharedv4: "true"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shinysorter-storagedir
spec:
  storageClassName: shinysorter-storagedir-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: shinysorter-supastoragedir-sc
  annotations:
    helm.sh/hook: pre-install
provisioner: pxd.portworx.com
parameters:
  repl: "1"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shinysorter-supastoragedir
spec:
  storageClassName: shinysorter-supastoragedir-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
