---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: "shinysorter-mongo-sc"
provisioner: pxd.portworx.com
parameters:
  repl: "1"
  fs: "xfs"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: shinysorter-importdir-sc
provisioner: pxd.portworx.com
parameters:
  repl: "1"
  sharedv4: "true"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shinysorter-importdir
spec:
  storageClassName: shinysorter-importdir-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: shinysorter-storagedir-sc
provisioner: pxd.portworx.com
parameters:
  repl: "1"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shinysorter-storagedir
spec:
  storageClassName: shinysorter-storagedir-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi