---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "shinysorter.fullname" . }}-supasmb
  labels:
    app: supasmb
spec:
  type: LoadBalancer
  selector:
    app: supasmb
  ports:
    - port: {{ .Values.smb.port }}
      targetPort: 445 # Can't change this in container, so change in service layer instead
      name: supasmb
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "shinysorter.fullname" . }}-supasmb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supasmb
  template:
    metadata:
      name: supasmb
      labels:
        app: supasmb
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: supasmb
          image: andyzhangx/samba:win-fix
          env:
            - name: PERMISSIONS
              value: "0777"
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "shinysorter.fullname" . }}-smbcreds
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "shinysorter.fullname" . }}-smbcreds
                  key: password
          args:
            [
              "-u",
              "$(USERNAME);$(PASSWORD)",
              "-s",
              "share;/smbshare/;yes;no;no;all;none",
              "-p",
            ]
          volumeMounts:
            - mountPath: /smbshare
              name: data-volume
          ports:
            - containerPort: 445
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: shinysorter-supastoragedir
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "shinysorter.fullname" . }}-smbcreds
stringData:
  username: {{ required "SMB username is required" .Values.smb.username}}
  password: {{ required "SMB password is required" .Values.smb.password}}
